[package]
name = "lloyd_massiah_when_i_work_take_home"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "*"
chrono = "0.4"
chrono-tz = "*"
